include: package:flutter_lints/flutter.yaml

linter:
  rules:
    file_names: false
    empty_catches: false
    use_key_in_widget_constructors: false
    avoid_function_literals_in_foreach_calls: false

analyzer:
  errors:
    todo: ignore
    must_be_immutable: ignore