blank_issues_enabled: true
contact_links:
  - name: RPMLauncher Discord Community
    url: https://discord.gg/5xApZtgV2u
    about: Join the RPMTW Discord community, where you can ask questions or discuss chat, etc...
  - name: RPMLauncher Discord 社群
    url: https://discord.gg/5xApZtgV2u
    about: 加入 RPMTW Discord 社群，您可在裡面詢問問題或討論聊天等...
