name: Build

on:
  push:
    branches:
      - main
      - develop
    paths:
      - "lib/**"
      - "pubspec.lo ck"
      - ".github/workflows/Build.yml"

  workflow_dispatch:

env:
  version_type: ${{ (github.ref =='refs/heads/main') && format('{0}', 'stable') || format('{0}', 'dev') }}
  rwl_version_full: ${{ secrets.VERSION  }}+${{ github.run_number }}
jobs:
  Build-Linux:
    if: ${{ !contains(github.event.head_commit.message,'[ci skip]') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@main
        with:
          flutter-version: 3.0.1
          cache: true
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install ninja-build libgtk-3-dev libblkid-dev
      - name: Build
        run: |
          dart pub global activate cider
          dart pub global run cider version ${{ env.rwl_version_full }}        
          flutter build linux --dart-define="build_id=${{ github.run_number }}" --dart-define="version_type=${{  env.version_type  }}" --dart-define="version=${{ secrets.VERSION  }}"
      - name: Upload File
        uses: actions/upload-artifact@v2
        with:
          name: RPMLauncher-Linux
          path: build/linux/x64/release/bundle
          retention-days: 1

  Linux-Snap:
    if: ${{ !contains(github.event.head_commit.message,'[ci skip]') }}
    runs-on: ubuntu-latest
    needs: ["Build-Linux"]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Download RPMLauncher Linux files
        uses: actions/download-artifact@v2
        with:
          name: RPMLauncher-Linux
          path: RPMLauncher-Linux
      - name: Install snapcraft
        uses: samuelmeuli/action-snapcraft@v1.2.0
        with:
          snapcraft_token: ${{ secrets.snapcraft_token }}
        continue-on-error: true
      - name: Install lxd
        uses: whywaita/setup-lxd@v1
      - name: Build and publish to snap store
        env:
          channel: ${{ (github.ref =='refs/heads/main') && format('{0}', 'stable') || format('{0}', 'beta') }}
        run: |
          snapcraft snap --output rpmlauncher.snap --use-lxd
          snapcraft upload ./rpmlauncher.snap --release=$channel
        continue-on-error: true

  Build-Windows:
    if: ${{ !contains(github.event.head_commit.message,'[ci skip]') }}
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@main
        with:
          flutter-version: 3.0.1
          cache: true
      - name: Build App
        run: |
          dart pub global activate cider
          dart pub global run cider version ${{ env.rwl_version_full }}
          flutter build windows --dart-define="build_id=${{ github.run_number }}" --dart-define="version_type=${{  env.version_type  }}" --dart-define="version=${{ secrets.VERSION  }}"
      - name: Build Installer
        run: |
          cd ${{ github.workspace }}/packageing/exe

          copy -r "${{ github.workspace }}/build/windows/runner/Release" ./

          copy C:\Windows\System32\msvcp140.dll ./Release
          copy C:\Windows\System32\vcruntime140.dll ./Release
          copy C:\Windows\System32\vcruntime140_1.dll ./Release

          copy ./app_icon.ico ./Release

          Remove-item alias:curl
          curl https://mlaan2.home.xs4all.nl/ispack/innosetup-6.2.1.exe --output innosetup.exe
          Start-Process .\innosetup.exe /VERYSILENT -Wait

          copy "${{ github.workspace }}\packageing\exe\Languages\ChineseTraditional.isl" "C:\Program Files (x86)\Inno Setup 6\Languages"
          copy "${{ github.workspace }}\packageing\exe\Languages\ChineseSimplified.isl" "C:\Program Files (x86)\Inno Setup 6\Languages"

          cd "C:\Program Files (x86)\Inno Setup 6"
          iscc "${{ github.workspace }}/packageing/exe/rpmlauncher.iss"
        shell: powershell
      - name: Upload Windows File (installer)
        uses: actions/upload-artifact@v2
        with:
          name: RPMLauncher-Windows
          path: ${{ github.workspace }}/packageing/exe/RPMLauncher-Windows-Installer.exe
          retention-days: 1
      - name: Upload Windows File (zip)
        uses: actions/upload-artifact@v2
        with:
          name: RPMLauncher-Windows-Zip
          path: ${{ github.workspace }}/packageing/exe/Release
          retention-days: 1

  Build-macOS:
    if: ${{ !contains(github.event.head_commit.message,'[ci skip]') }}
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@main
        with:
          flutter-version: 3.0.1
          cache: true
      - name: Build
        run: |
          flutter pub get
          pod repo update
          dart pub global activate cider
          dart pub global run cider version ${{ env.rwl_version_full }}                 
          flutter build macos --dart-define="build_id=${{ github.run_number }}" --dart-define="version_type=${{  env.version_type  }}" --dart-define="version=${{ secrets.VERSION  }}" --release
          cp assets/images/macOS_logo_icon.icns build/macos/Build/Products
          cd build/macos/Build/Products
          brew install create-dmg
          create-dmg \
          --volname "RPMLauncher Installer (${{ env.rwl_version_full }})" \
          --volicon "macOS_logo_icon.icns" \
          --window-pos 200 120 \
          --window-size 800 529 \
          --icon "rpmlauncher.app" 260 250 \
          --hide-extension "rpmlauncher.app" \
          --app-drop-link 540 250 \
          --hdiutil-quiet \
          "RPMLauncher-macOS-Installer.dmg" \
          "Release/"
        continue-on-error: true
      - name: Upload File
        uses: actions/upload-artifact@v2
        with:
          name: RPMLauncher-MacOS
          path: build/macos/Build/Products/RPMLauncher-macOS-Installer.dmg
          retention-days: 1
  Release:
    needs: ["Build-Linux", "Build-Windows", "Build-macOS"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603
      - name: Download files
        uses: actions/download-artifact@v2
      - run: chmod +x RPMLauncher-Linux/RPMLauncher
      - name: Zip linux
        uses: thedoctor0/zip-release@master
        with:
          type: "zip"
          filename: "RPMLauncher-Linux.zip"
          path: RPMLauncher-Linux

      - name: Zip windows
        uses: thedoctor0/zip-release@master
        with:
          type: "zip"
          filename: "RPMLauncher-Windows.zip"
          path: RPMLauncher-Windows-Zip

      - name: "AppImage build"
        run: |
          sudo apt install -y python3-pip python3-setuptools patchelf desktop-file-utils libgdk-pixbuf2.0-dev fakeroot strace fuse
          sudo wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage -O /usr/local/bin/appimagetool
          sudo chmod +x /usr/local/bin/appimagetool
          sudo pip3 install appimage-builder
          appimage-builder --recipe packageing/AppImageBuilder.yml

      - name: "Deb package build"
        run: |
          cp -r RPMLauncher-Linux packageing/deb/opt/RPMLauncher/Binary
          sed -i 's/${VERSION}/${{ env.rwl_version_full }}/g' packageing/deb/DEBIAN/control
          fakeroot dpkg-deb --build packageing/deb "RPMLauncher-Linux.deb"

      - name: Upload releases
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.API_TOKEN_GITHUB }}"
          prerelease: ${{ (github.ref =='refs/heads/main') && format('{0}', 'false') || format('{0}', 'true') }}
          automatic_release_tag: ${{ env.rwl_version_full }}
          title: ${{ env.rwl_version_full }}
          files: |
            RPMLauncher-Windows/RPMLauncher-Windows-Installer.exe
            RPMLauncher-Windows.zip
            RPMLauncher-Linux.zip
            RPMLauncher-Linux.AppImage
            RPMLauncher-Linux.deb
            RPMLauncher-MacOS/RPMLauncher-macOS-Installer.dmg

      - name: Upload to Arch User Repository
        env:
          packageVersion: ${{ env.rwl_version_full }}
          PRIVATE: ${{ secrets.PRIVATE }}
        run: |
          hasht=$(sha256sum "RPMLauncher-Linux.zip" | cut -d" " -f1)
          mkdir ~/.ssh
          touch ~/.ssh/known_hosts
          ssh-keyscan -v -t ssh-rsa aur.archlinux.org >>~/.ssh/known_hosts
          echo "Host aur.archlinux.org" >> ~/.ssh/config
          echo "  IdentityFile ~/.ssh/aur" >> ~/.ssh/config
          echo "  User aur" >> ~/.ssh/config
          echo "$PRIVATE" >> ~/.ssh/aur
          chmod -vR 600 ~/.ssh/aur
          ssh-keygen -vy -f ~/.ssh/aur >~/.ssh/aur.pub
          git clone ssh://aur@aur.archlinux.org/rpmlauncher-bin 
          cd rpmlauncher-bin
          sed -i "s/sha256sums=.*/sha256sums=('$hasht'/" PKGBUILD
          rm .SRCINFO
          sed -i "s/pkgver=.*/pkgver=$packageVersion/" PKGBUILD
          echo "pkgbase = rpmlauncher-bin" >> .SRCINFO
          echo "	pkgdesc = A better Minecraft Launcher that supports cross-platform and many functionalities for you to explore! " >> .SRCINFO
          echo "  pkgver = $packageVersion" >> .SRCINFO
          echo "  pkgrel = 1" >> .SRCINFO
          echo "  arch = x86_64" >> .SRCINFO
          echo "  license = GPL3" >> .SRCINFO
          echo "  makedepends = rsync" >> .SRCINFO
          echo "  provides = rpmlauncher" >> .SRCINFO
          echo "  conflicts = rpmlauncher" >> .SRCINFO
          echo "  source = https://github.com/RPMTW/RPMLauncher/releases/download/$packageVersion/RPMLauncher-Linux.zip" >> .SRCINFO
          echo "  source = RPMLauncher.desktop" >> .SRCINFO
          echo "  source = https://github.com/RPMTW/RPMLauncher/raw/develop/assets/images/Logo.png" >> .SRCINFO
          echo "  sha256sums = $hasht" >> .SRCINFO
          echo "  sha256sums = af2720db5735cc5e9fb9fe76e20f12d51da452e5360fb90a7086f360efbb3828" >> .SRCINFO
          echo "  sha256sums = 4fb011f8924ae51231875788181bd5800345500745364fb921c22448f368d570" >> .SRCINFO
          echo "  " >> .SRCINFO
          echo "pkgname = rpmlauncher-bin" >> .SRCINFO
          git config --global user.email "shiue.kyle@gmail.com"
          git config --global user.name "KyleUltimate"
          git add PKGBUILD .SRCINFO
          git commit -m "Auto update to $packageVersion"
          git remote add aur "ssh://aur@aur.archlinux.org/rpmlauncher-bin" 
          git push origin master

      - name: Create sentry release
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: rpmtw
          SENTRY_PROJECT: rpmlauncher
        with:
          environment: ${{ (github.ref =='refs/heads/main') && format('{0}', 'production') || format('{0}', 'debug') }}
          sourcemaps: "./lib"
          version: rpmlauncher@${{ env.rwl_version_full }}
      - name: Run UpdateJson Script
        run: |
          cd ${{ github.workspace }}/scripts/UpdateJson
          dart pub get
          dart run bin/main.dart --version ${{ secrets.VERSION  }} --build_id "${{ github.run_number }}" --type "${{ env.version_type }}" --changelog "${{ github.event.head_commit.message }}"
        continue-on-error: true
      - name: Update Json
        uses: dmnemec/copy_file_to_another_repo_action@3fe42250d47e0764da9de9939b151b09a26e5857
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: "${{ github.workspace }}/scripts/UpdateJson/update.json"
          destination_repo: "RPMTW/RPMTW-website-data"
          destination_folder: "data/RPMLauncher"
          user_email: "rpmtw666@gmail.com"
          user_name: "RPMTW Bot"
          commit_message: "Update RPMLauncher Json"

  Analyze:
    if: ${{ !contains(github.event.head_commit.message,'[ci skip]') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@main
        with:
          flutter-version: 3.0.1
          cache: true
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install ninja-build libgtk-3-dev libblkid-dev
          flutter pub get
      - name: Analyze Flutter
        uses: zgosalvez/github-actions-analyze-dart@v1
        continue-on-error: true

  Coverage:
    if: ${{ !contains(github.event.head_commit.message,'[ci skip]') }}
    strategy:
      matrix:
        runs-on: [ubuntu-latest, windows-latest, macos-latest]
      fail-fast: false
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@main
        with:
          flutter-version: 3.0.1
          cache: true
      - name: Generate coverage
        run: |
          flutter pub get
          flutter test --coverage
        shell: bash
        continue-on-error: true
      - name: Upload to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage/lcov.info
